[tool.poetry]
name = "flask-poetry"
version = "0.1.0"
description = ""
authors = ["Edison Garcia"]

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^2.0.1"
requests = "^2.26.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
